# docker-compose -f docker-compose.yml -f docker-compose-hugo-build.yml up --build hugo-build-org-foolscap-podcast  && docker logs docker-dougbealcom_hugo-build-org-foolscap-podcast_1
version: '3'

services:
  hugo-build-org-foolscap-podcast:
    build: hugo-build
    volumes:
      - org.foolscap.podcast:/build/
      - org.foolscap.podcast_media:/build/media/
    working_dir: /build/
    
    command: --debug --verbose --cacheDir /build/cache --verboseLog --log --logFile /dev/stdout



# docker-compose -f docker-compose.yml -f docker-compose.yarn.yml up --build open-hugo-yarn  && docker logs docker-dougbealcom_open-hugo-yarn_1

  open-hugo-yarn:
    build: open-hugo-yarn
    volumes:
      - hugo_org_foolscap_open:/hugo_org.foolscap.open/
    working_dir: /hugo_org.foolscap.open/
    
    command: sh -c "pwd && ls -al && (( cd themes/hugo-theme-openspace/assets/js && yarn install )) && (( cd themes/hugo-theme-openspace/assets/scss && yarn install ))"
