version: '3'

# see .env for shared variabvles
services:
  letsencrypt:
    image: certbot/certbot
    volumes:
      - well-known:/root/work/www/.well-known
      - letsencrypt:/root/work/letsencrypt
    command: >-
      certonly --verbose --webroo
      --agree-tos --non-interactive
      -m cert@dougbeal.com
      --webroot-path=/root/work/www
      --work-dir=/root/work/work
      --logs-dir=/root
      --config-dir=/root/work/letsencrypt
      -d stage.dougbeal.com

#      --staging --debug-challenges      
#      --agree-tos --non-interactive
volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/letsencrypt
      o: bind
  well-known:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/well-known
      o: bind
