version: '3'

# see .env for shared variabvles
services:
  database:
    image: mariadb:5.5
    volumes:
      - database:/var/lib/mysql
      - import-database:/docker-entrypoint-initdb.d
    restart: on-failure
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_TCP_PORT: "${DATABASE_PORT}"
    networks:
      - backend
      - debug
    # docker exec indieweb_database_1 "mysql -u ${MYSQL_USER} -p ${MYSQL_USER} < /sql/dougbeal_wp116.sql"
    
  webserver-wordpress:
    build: webserver-wordpress
    depends_on:
      - wordpress
    links:
      - wordpress    
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      # wait for v3.2 to be more widespread
      # - type: volume
      #   source: public-key
      #   target: ${WEBSERVER_ROOT}/.well-known/public-key
      #   volume:
      #     nocopy: true
      #     read_only: true
      - well-known:${WEBSERVER_ROOT}/.well-known:ro
      - letsencrypt:/etc/letsencrypt:ro
      - wordpress:${WEBSERVER_ROOT}
      - wordpress-themes:${WEBSERVER_ROOT}/wp-content/themes
      - wordpress-plugins:${WEBSERVER_ROOT}/wp-content/plugins
    environment:
      NGINX_HOST: ${HOSTNAME}
      NGINX_PORT: 80
      WORDPRESS_HOST: "${WORDPRESS_HOST}"
    networks:
      - frontend
      - debug
      - backend

  wordpress:
    depends_on:
      - database
    build: wordpress
    volumes:
      - wordpress:${WORDPRESS_PATH}
      - wordpress-themes:${WORDPRESS_PATH}/wp-content/themes
      - wordpress-plugins:${WORDPRESS_PATH}/wp-content/plugins
    links:
      - database
    environment:
      WORDPRESS_PATH: ${WEBSERVER_ROOT}/wordpress
      WORDPRESS_DB_HOST: "${DATABASE_HOST}:${DATABASE_PORT}"
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - backend
      - debug
    command: "/wait-for ${DATABASE_HOST}:${DATABASE_PORT} -- php-fpm"

volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/letsencrypt
      o: bind
  well-known:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/well-known
      o: bind              
  database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/database
      o: bind    
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/wordpress
      o: bind
  wordpress-themes:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/wordpress-themes
      o: bind
  wordpress-plugins:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/wordpress-plugins
      o: bind      
  import-wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/import-wordpress
      o: bind
  import-database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/import-database
      o: bind
  sempress:      
  sempress-child:
  nginx-config:
  sql:


networks:
  frontend:
    driver: bridge
  debug:
    driver: bridge
  backend:
    internal: true
