version: '3'

# see .env for shared variabvles
services:
  letsencrypt:
    image: certbot/certbot
    volumes:
      - well-known:/root/work/www/.well-known
      - letsencrypt:/root/work/letsencrypt
    command: >-
      certonly --verbose --webroot --expand
      --agree-tos --non-interactive
      -m cert@dougbeal.com
      --webroot-path=/root/work/www
      --work-dir=/root/work/work
      --logs-dir=/root
      --config-dir=/root/work/letsencrypt
      --cert-name=dougbeal.com
      -d dougbeal.com -d u.dougbeal.com -d stage.dougbeal.com -d www.dougbeal.com
      -d crow.moe -d crw.moe
      -d ek.dougbeal.com -d together.dougbeal.com -d www.crow.moe -d www.crw.moe
      -d foolscap.dougbeal.com -d svc.foolscap.org
      -d open.foolscap.org -d form.foolscap.org -d form.foolscap.dougbeal.com -d open.foolscap.dougbeal.com
      -d podcast.foolscap.org -d podcast.foolscap.dougbeal.com
      -d hwc.dougbeal.com -d indieweb.dougbeal.com

# -d indieping.me enable later
#      --staging --debug-challenges
#      --agree-tos --non-interactive
volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/letsencrypt
      o: bind
  well-known:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/well-known
      o: bind
