version: '3'

# see .env for shared variabvles
services:
  letsencrypt:
    userns_mode: "host" # run as root!?!?!
    image: certbot/certbot
    volumes:
      - well-known:./www/well-known
      - letsencrypt:./letsencrypt
    command: >-
      certonly --webroot
      -m cert@dougbeal.com
      --agree-tos --non-interactive
      --webroot-path=./www
      --work-dir=./work
      --logs-dir=./
      --config-dir=./letsencrypt
      -d liw.dougbeal.com -d stage.dougbeal.com -d micro.liw.dougbeal.com

volumes:
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/letsencrypt
      o: bind
  well-known:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/well-known
      o: bind
