version: '3'

# see .env for shared variabvles
services:
  database:
    image: mariadb:5.5
    volumes:
      - database:/var/lib/mysql
      - import-database:/docker-entrypoint-initdb.d:ro
    restart: on-failure
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: rootwordpress
      MYSQL_DATABASE: ${WORDPRESS_DATABASE_NAME} # init .sql files are loaded into it
      MYSQL_USER: ${WORDPRESS_DATABASE_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    networks:
      - backend
      - debug
    # docker exec indieweb_database_1 "mysql -u ${MYSQL_USER} -p ${MYSQL_USER} < /sql/dougbeal_wp116.sql"

  webserver-wordpress:
    build: webserver-wordpress
    depends_on:
      - wordpress
    links:
      - wordpress
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      # wait for v3.2 to be more widespread
      # - type: volume
      #   source: public-key
      #   target: ${WEBSERVER_ROOT}/.well-known/public-key
      #   volume:
      #     nocopy: true
      #     read_only: true
      - well-known:${WEBSERVER_ROOT}/.well-known:ro
      - letsencrypt:/etc/letsencrypt:ro
      - wordpress_com_dougbeal:${WEBSERVER_ROOT}
      - wordpress_com_dougbeal-themes:${WEBSERVER_ROOT}/wp-content/themes
      - wordpress_com_dougbeal-plugins:${WEBSERVER_ROOT}/wp-content/plugins
    environment:
      NGINX_HOST: ${HOSTNAME}
      NGINX_PORT: 80
      WORDPRESS_HOST: "${WORDPRESS_HOST}"
    networks:
      - frontend
      - debug
      - backend

  wordpress:
    depends_on:
      - database
    build: wordpress
    volumes:
      - wordpress_com_dougbeal:${WORDPRESS_PATH}
      - wordpress_com_dougbeal-themes:${WORDPRESS_PATH}/wp-content/themes
      - wordpress_com_dougbeal-plugins:${WORDPRESS_PATH}/wp-content/plugins
      - import-wordpress:/import-wordpress:ro
    links:
      - database
    environment:
      WORDPRESS_TABLE_PREFIX: "wphk_" # match legacy database
      WORDPRESS_PATH: ${WEBSERVER_ROOT}/wordpress
      WORDPRESS_DB_HOST: "${DATABASE_HOST}:${DATABASE_PORT}"
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
    networks:
      - backend
      - debug
    command: "php-fpm"

  together:
    depends_on:
      - database
    build: together
    volumes:
      - together:/root/together
    
# TODO - need to generate volumes based on sites
volumes:
  together:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/together
      o: bind    
  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/letsencrypt
      o: bind
  well-known:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/well-known
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/database
      o: bind
  wordpress_com_dougbeal:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/${SITE}
      o: bind
  wordpress_com_dougbeal-themes:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/${SITE}_d/themes
      o: bind
  wordpress_com_dougbeal-plugins:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/${SITE}_d/plugins
      o: bind
  import-wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/import-wordpress
      o: bind
  import-database:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/import-database
      o: bind



networks:
  frontend:
    driver: bridge
  debug:
    driver: bridge
  backend:
    internal: true
