        baseURL = "http://podcast.foolscap.org/"
        languageCode = "en-us"
        title = "The Voices of Foolscap"
        theme = "castanet"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
        episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "books"
    parent = "resources"
[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "books"
    parent = "resources"

[params]
        site_theme = "purple"
        favicon = "icon/favicon.ico"
        description = "A look back at Foolscaps of yore."
        media_prefix = "https://podcast.foolscap.org/media/"
        copyright_notice = "Copyright 2019 [Foolscap](https://foolscap.org)"

[params.feed]
        explicit = "no"
        copyright_notice = "Copyright 2019 Foolscap"
        itunes_author = "Douglas Beal"
        itunes_summary = "A look back at Foolscaps of yore."
        itunes_owner_name = "Foolscap"
        itunes_owner_email = "info@foolscap.org"
        itunes_image = "https://www.foolscap.org/content/images/2014/Apr/Foolscap-poster-800px.png"
        itunes_top_category = "Arts"
        itunes_first_sub_category = "Literature"
        itunes_second_sub_category = "Convention"

[params.social]
        twitter = "foolscapcon"
        twitter_domain = "foolscap.org"

[params.authors]
        [params.authors.dougbeal]
        name = "Douglas Beal"
        thumbnail = "https://secure.gravatar.com/avatar/4aef6f46cd0c5c51bbf5c15d4e66b35e?s=125&d=default&r=g"
        bio = "[https://dougbeal.com](https://dougbeal.com) Freelance Developer. IndieWeb Meetup Seattle Organizer. Fountain Pen Enthusiast. Foolscap Captain 22020."


[params.links]
        [params.links.foolscap]
        name = "Foolscap"
        url = "http://foolscap.org"
